//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Messenger.h
//  Source: Messenger.idl
//  Generated: Wed Feb 12 15:30:23 2020
//  OpenSplice 6.9.181018OSS
//  
//******************************************************************
#ifndef _MESSENGER_H_
#define _MESSENGER_H_

#include "sacpp_mapping.h"
#include "examples_export.h"


namespace Messenger
{
   struct Message;

   struct OS_EXAMPLE_API Message
   {
         DDS::Long subjectId;
         DDS::Double time;
         DDS::String_mgr from;
         DDS::String_mgr topicName;
         DDS::String_mgr text;
         DDS::Double data;
   };

   typedef DDS_DCPSStruct_var < Message> Message_var;
   typedef DDS_DCPSStruct_out < Message> Message_out;
}




#endif
