//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Messenger.cpp
//  Source: Messenger.idl
//  Generated: Wed Feb 12 15:30:23 2020
//  OpenSplice 6.9.181018OSS
//  
//******************************************************************

#include "Messenger.h"




