//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Messenger.cpp
//  Source: Messenger.idl
//  Generated: Sun Mar 29 12:23:32 2020
//  OpenSplice 6.9.181018OSS
//  
//******************************************************************

#include "Messenger.h"




